General:
  SEED: 42
  INTERSECTION_THRESHOLD: 0.01
  FATNESS: 0.5
  NUM_SCENES: 10   
  RED_OR_GREEN: 'green'
  VIDEO_LEN: 6
  FPS: 30
  DEGREE: 15
  POINT:
  PROJECTION_X: [-1, 3]
  PROJECTION_Y: [-1.5, 1.5]
  ROT_DISCRETE: False
  OUTPUT_PATH: '/ceph/home/panchang/TowerTask/TowerTaskVideos/20'
Scene:
  num_blocks: 20
  num_colors: 
    yellow: 10
    blue: 9
    white: 1 
  sizes: 
    (0.5, 0.5, 1.5): 11
    (1.5, 0.5, 0.5): 9
  rot_range: [0, 360]
  material: "wood"