General:
  SEED: 42
  INTERSECTION_THRESHOLD: 0.01
  FATNESS: 0.5
  NUM_SCENES: 10   
  RED_OR_GREEN: 'red' #'green'
  VIDEO_LEN: 6
  FPS: 30
  DEGREE: 15
  POINT:
  PROJECTION_X: [-3, 1]  #[-1, 3]
  PROJECTION_Y: [-1.5, 1.5]
  ROT_DISCRETE: False
  OUTPUT_PATH: '/ceph/home/panchang/TowerTask/TowerTaskVideos/22'
Scene:
  num_blocks: 22
  num_colors: 
    yellow: 11
    blue: 10
    white: 1
  sizes: 
    (0.5, 0.5, 1.5): 12
    (1.5, 0.5, 0.5): 10
  rot_range: [0, 360]
  material: "wood"