General:
  SEED: 42
  INTERSECTION_THRESHOLD: 0.01
  FATNESS: 0.5
  NUM_SCENES: 10   
  RED_OR_GREEN: 'green'
  VIDEO_LEN: 6
  FPS: 30
  DEGREE: 15
  POINT:
  PROJECTION_X: [-1, 3]
  PROJECTION_Y: [-1.5, 1.5]
  ROT_DISCRETE: False
  OUTPUT_PATH: 'D:/Desktop/University/Research/Intuitive_Physics/TowerTask'
Scene:
  num_blocks: 24
  num_colors: 
    yellow: 11 
    blue: 11
    white: 2
  sizes: 
    (0.5, 0.5, 1.5): 14
    (1.5, 0.5, 0.5): 10
  rot_range: [0, 360]
  material: "wood"