General:
  SEED: 42
  INTERSECTION_THRESHOLD: 0.01
  FATNESS: 0.5
  NUM_SCENES: 10   
  RED_OR_GREEN: 'green'
  VIDEO_LEN: 6
  FPS: 30
  DEGREE: 15
  POINT:
  PROJECTION_X: [-1, 3]
  PROJECTION_Y: [-1.5, 1.5]
  ROT_DISCRETE: False
  OUTPUT_PATH: '/data/qingjingfan/Documents/TowerTask/TowerTaskVideos/green/28'
Scene:
  num_blocks: 28
  num_colors: 
    yellow: 13 
    blue: 12
    white: 3
  sizes: 
    (0.5, 0.5, 1.5): 16 
    (1.5, 0.5, 0.5): 12
  rot_range: [0, 360]
  material: "wood"